### ISSUE TITLE
trouble on surface pro 7

### ISSUE THREAD

**Issue by liangbohk** [personalizedrefrigerator/js-draw#23] opened 2023-07-05 03:27 UTC
# Describe the bug
When I draw a path on surface pro with surface pen, last path disappears. However with my finger I draw a path, last path remains, everything is good

# Platform
 - OS: Win11
 - Browser:  Joplin
 - Version: 2.11.11

**Comment by personalizedrefrigerator** [comment] 2023-07-05 03:50
## Additional information that would be helpful
Are you also experiencing this in the [web version of js-draw](https://personalizedrefrigerator.github.io/js-draw/example/index.html)?

## What I think the issue is
Here's what I think is causing this: On some browsers, pen up events might also send, in addition to `pointerup` events, other events (e.g. `touchcancel`, `touchend`, or `pointercancel` events, I'm not sure which). As such, a potential fix is to ignore `pointercancel` and touch-related events at the end of a stylus-triggered stroke.

**Comment by personalizedrefrigerator** [comment] 2023-07-05 05:49
I've published a new version of the Joplin plugin that might fix the issue for strokes.

**If it does fix the issue**, is there still a similar issue with the eraser, text, and selection tools? 

**If it does not fix the issue**, are you experiencing the issue on the [web version](https://personalizedrefrigerator.github.io/js-draw/example/index.html) (please test with Google Chrome or Microsoft Edge)? (If so, [an input log](https://personalizedrefrigerator.github.io/js-draw/debugging/stroke-logging/) would be helpful).

**Comment by personalizedrefrigerator** [comment] 2023-07-05 15:25
Thank you for testing this! If you have any other feedback, feel free to post here or open another GitHub issue about it!

**Notes:**
- Several months ago, a similar issue was reported when using js-draw in Microsoft Edge. Updating Microsoft Edge fixed the issue. If this was fixed in a somewhat-recent version of Chromium, because Joplin uses an older electron release, it probably lacks this fix.
- The changes made related to this issue were only related to the pen tool. It's possible there are similar issues related to the other tools (e.g. each stroke with the eraser tool might generate two erase events).

**Closed by personalizedrefrigerator** 2023-07-05 15:25 UTC
Labels: bug
